apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vhoca6oy3-nodejs
  janus-idp.io/tekton: vhoca6oy3-nodejs
  backstage.io/kubernetes-id: vhoca6oy3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vhoca6oy3-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
