apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vhoca6oy3-nodejs-gitops
  description: This is GitOps manifest for vhoca6oy3-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=vhoca6oy3-nodejs
    backstage.io/kubernetes-id: vhoca6oy3-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: vhoca6oy3-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:vhoca6oy3-nodejs
